### ISSUE TITLE
pi pro with google smart extension

### ISSUE THREAD

**Issue by PitchAbyss** [DeskPi-Team/deskpi#131]
hi please can someone help

i have connected pi pro to a smart extension that can be controlled by alexa or google assistant and i have set timers to turn off pi pro at 2am at night and turn on at 8 am in morning...but its been whole day i couldnt figure out what happened i just went near to pi box in other room to check the lights were red that means i have to manually press the power button to start it...is there anyway i can fix this ??

please help if anyone aware of this

**Comment by yoyojacky** [comment]
there is a switch on board `always on`, please toggle it to `en`  means enable, it will never cut of the power when you shutdown the raspberry pi, and if you can wake it up from command line, it will OK. but as I know, if you want to reset the raspberry pi, you need to adding external hardware to trigger `RUN, GLOBAL_EN` pin on Raspberry Pi. and if you shutdown the system, do not send `POWER_OFF` signal via `/dev/ttyUSB0` to MCU on deskpi daughter board. because the sigal will let the MCU cut off the power, so that you have to press the power button again to power it on.
